"""
Generated By: Cursor (Claude Sonnet 4.5)

Project-specific configuration constants for ap-cull-lights.
These are specific to this tool and not shared across projects.
"""

# File pattern constants
INPUT_PATTERN_ALL = ".*"
